name: CI/CD Frontend

# ============================================================
# Trigger: Se activa con push en la rama deploy--
# ============================================================
on:
  push:
    branches:
      - main
    paths:
      - 'front_despacho/**' # Cambia esto por el nombre real de tu carpeta


env:
  AWS_REGION: us-east-1
  CLUSTER: innovatech-cluster
  SERVICE: frontend-service
  ECR_REPOSITORY: innovatech-frontend

jobs:
  deploy:
    name: Deploy Frontend a AWS ECS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar las credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Login en ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: Build y Push de imagen frontend
        run: |
          docker build --platform linux/amd64 \
          -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:latest \
          ./front_despacho
          
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:latest
      
      - name: Forzar un redespliegue en ECS
        run: |
          aws ecs update-service \
          --cluster ${{ env.CLUSTER }} \
          --service ${{ env.SERVICE }} \
          --force-new-deployment